name: gh-pages

on: [push]
jobs:
  build:
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.x
        
    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .NuGets
      run: dotnet nuget add source --username bvo4 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/bvo4/index.json"
      
    - name: dotnet workload restore
      run: dotnet workload restore
    - name: Publish with dotnet
      run: dotnet publish src/Client/Client.csproj -c Release -o release --nologo
    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: src/Client/wwwroot # The folder the action should deploy.
        SINGLE_COMMIT: true
